# Configuration file for the Sphinx documentation builder.
# Generated by Lative. See https://www.sphinx-doc.org/en/master/usage/configuration.html

project = 'webSMLM'
author = 'Johannes Hohlbein'
copyright = '2026, Hohlbein'

root_doc = "index"

extensions = [
    'sphinx.ext.mathjax',
    "myst_parser",
]

templates_path = [
    '_templates'
]

exclude_patterns = [
    '_build',
    'Thumbs.db',
    '.DS_Store'
]

source_suffix = {
    ".md": "markdown",
}

myst_heading_anchors = 6

html_theme = 'sphinx_rtd_theme'


# Render numbered figures/tables 
numfig = True
